# A scrape configuration scraping a Node Exporter and the Prometheus server
# itself.

global:
  scrape_interval: 10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 2s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).


scrape_configs:
  # Scrape Prometheus itself every 5 seconds.
  - job_name: 'csvserver'
    metrics_path: /metrics
    static_configs:
      - targets:
        - '192.168.0.104:9393'
