version: "3"
services:
  application:
    container_name: application
    hostname: application
    image: infracloudio/csvserver:latest
    ports:
      - "9393:9300"
    volumes:
      - "/home/swapnil/csvserver/inputdata:/csvserver/inputdata"
    environment:
      CSVSERVER_BORDER: Orange

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:v2.22.0
    ports:
      - 9090:9090
    volumes:
      - "/home/swapnil/csvserver/solution/:/etc/prometheus"
~                                                                
